change5

diff --git a/sources/dockerfile b/sources/dockerfile
--- a/sources/dockerfile
+++ b/sources/dockerfile
@@ -1,5 +1,5 @@
 # Phase de build
-FROM klakegg/hugo:latest as builder
+FROM klakegg/hugo:0.92.2 as builder
 
 # Copier le contenu du site Hugo dans le conteneur
 COPY . /src
@@ -7,8 +7,9 @@ COPY . /src
 # Se déplacer dans le répertoire du site Hugo
 WORKDIR /src
 
-# Exécuter la commande Hugo pour générer le site statique
-RUN hugo --minify
+# Exécutez la commande Hugo pour générer le site statique
+RUN hugo --minify || (echo "Hugo build failed" && exit 1)
+
 
 # Phase de run
 FROM nginx:latest as production
